"""initial schema

Revision ID: 1ed7e8f2e432
Revises: 
Create Date: 2026-03-23 13:47:43.678760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ed7e8f2e432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria_configs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'version', name='uq_criteria_configs_tenant_version')
    )
    op.create_index(op.f('ix_criteria_configs_tenant_id'), 'criteria_configs', ['tenant_id'], unique=False)
    op.create_table('deals',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_channel', sa.String(length=64), nullable=False),
    sa.Column('source_sender', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTED', 'FAILED', 'SCORED', 'DECIDED', name='dealstatus', native_enum=False), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_deals_tenant_content_hash')
    )
    op.create_index(op.f('ix_deals_content_hash'), 'deals', ['content_hash'], unique=False)
    op.create_index(op.f('ix_deals_status'), 'deals', ['status'], unique=False)
    op.create_index(op.f('ix_deals_tenant_id'), 'deals', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('DEAL_UPLOADED', 'EXTRACTION_STARTED', 'EXTRACTION_COMPLETED', 'EXTRACTION_FAILED', 'SCORING_COMPLETED', 'DECISION_MADE', 'CRITERIA_UPDATED', 'DEAL_RETRIED', name='auditaction', native_enum=False), nullable=False),
    sa.Column('from_status', sa.Enum('UPLOADED', 'EXTRACTED', 'FAILED', 'SCORED', 'DECIDED', name='dealstatus', native_enum=False), nullable=True),
    sa.Column('to_status', sa.Enum('UPLOADED', 'EXTRACTED', 'FAILED', 'SCORED', 'DECIDED', name='dealstatus', native_enum=False), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_deal_id'), 'audit_logs', ['deal_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('criteria',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('criterion_type', sa.Enum('MUST_HAVE', 'NICE_TO_HAVE', 'DEALBREAKER', name='criteriontype', native_enum=False), nullable=False),
    sa.Column('operator', sa.String(length=16), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['criteria_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_criteria_config_id'), 'criteria', ['config_id'], unique=False)
    op.create_table('deal_scores',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('criteria_config_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('criterion_results', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criteria_config_id'], ['criteria_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_scores_deal_id'), 'deal_scores', ['deal_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('extraction_run', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('field_status', sa.Enum('FOUND', 'INFERRED', 'MISSING', name='fieldextractionstatus', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='confidencelevel', native_enum=False), nullable=False),
    sa.Column('overall_confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', 'NONE', name='confidencelevel', native_enum=False), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_deal_id'), 'extracted_fields', ['deal_id'], unique=False)
    op.create_table('deal_decisions',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('PASSED', 'PURSUING', name='decisiontype', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('score_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['deal_scores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_decisions_deal_id'), 'deal_decisions', ['deal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deal_decisions_deal_id'), table_name='deal_decisions')
    op.drop_table('deal_decisions')
    op.drop_index(op.f('ix_extracted_fields_deal_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_deal_scores_deal_id'), table_name='deal_scores')
    op.drop_table('deal_scores')
    op.drop_index(op.f('ix_criteria_config_id'), table_name='criteria')
    op.drop_table('criteria')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deal_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_deals_tenant_id'), table_name='deals')
    op.drop_index(op.f('ix_deals_status'), table_name='deals')
    op.drop_index(op.f('ix_deals_content_hash'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('ix_criteria_configs_tenant_id'), table_name='criteria_configs')
    op.drop_table('criteria_configs')
    # ### end Alembic commands ###
